# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171119_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
